version: '3'

services:
  graffinity-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graffinity
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    labels:
      collect_logs_with_filebeat: "true"

  graffinity-backend:
    image: 445007777844.dkr.ecr.eu-central-1.amazonaws.com/graffinity-backend
    ports:
      - "8080:8080"
    depends_on:
      - graffinity-db
    env_file:
      - ./prod.env
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  graffinity-frontend:
    image: 445007777844.dkr.ecr.eu-central-1.amazonaws.com/graffinity-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - graffinity-backend
    env_file:
      - ./prod.front.env
    volumes:
      - /etc/ssl/live/:/etc/ssl/live/
    labels:
      collect_logs_with_filebeat: "true"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.0
    volumes:
      - ./config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro # Additional information about containers
      - ./config/filebeat-data:/usr/share/filebeat/data:rw # Persistence data
    user: root # Allow access to log files and docker.sock
    restart: on-failure
    env_file:
      - ./prod.env

volumes:
  prometheus_data: {}
  grafana_data: {}
