version: '3.7'

services:
  test-db:
    image: postgres:latest
    restart: always
    container_name: graffinity-test
    hostname: graffinity-test
    ports:
      - '5439:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  db:
    image: postgres:latest
    container_name: graffinity
    restart: always
    hostname: graffinity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graffinity
    volumes:
      - .db:/var/lib/postgresql/
    ports:
      - "5433:5432"
