version: '3'

services:
  graffinity-db:
    image: postgres:14.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graffinity
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  graffinity-backend:
    image: 445007777844.dkr.ecr.eu-central-1.amazonaws.com/graffinity-backend
    ports:
      - "8080:8080"
    depends_on:
      - graffinity-db
    env_file:
      - ./.env
    labels:
      decode_log_event_to_json_object: "true"

  graffinity-frontend:
    image: 445007777844.dkr.ecr.eu-central-1.amazonaws.com/graffinity-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - graffinity-backend
    env_file:
      - ./.env
    volumes:
      - /etc/ssl/live/:/etc/ssl/live/

volumes:
  prometheus_data: {}
  grafana_data: {}
