version: '3'

services:
  graffinity-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graffinity
    volumes:
      - /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  graffinity-backend:
    image: 445007777844.dkr.ecr.eu-central-1.amazonaws.com/graffinity-backend:latest
    depends_on:
      - graffinity-db
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    labels:
      decode_log_event_to_json_object: "true"

  graffinity-frontend:
    image: 445007777844.dkr.ecr.eu-central-1.amazonaws.com/graffinity-frontend:latest
    depends_on:
      - graffinity-backend
    env_file:
      - ./.env
    volumes:
      - /etc/ssl/:/etc/ssl/
    ports:
      - "80:80"
      - "443:443"

volumes:
  prometheus_data: {}
  grafana_data: {}
