# Use root/example as user/password credentials
version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: graffinity
    restart: always
    hostname: graffinity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graffinity
    volumes:
      - .db:/var/lib/postgresql/
    ports:
      - "5433:5432"
