version: '3'

services:
  test-db:
    image: postgres:15
    restart: always
    container_name: test
    hostname: test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - '5435:5432'
    volumes:
      - .db:/var/lib/postgresql/

  db:
    image: postgres:15
    container_name: graffinity
    restart: always
    hostname: graffinity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graffinity
    volumes:
      - .db:/var/lib/postgresql/
    ports:
      - "5433:5432"
