name: backend continuous integration

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
      - name: Run prettier
        run: npx prettier --check .

      - name: Install dependencies
        run: npm ci