name: backend continuous integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - ${{ secrets.DB_PORT }}:5432
    env:
      DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Run prettier
        run: npx prettier --check .

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present 

      - name: Migrate the database
        run: npx prisma migrate deploy

      - name: Run tests
        run: npm run test
