name: backend continuous integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Run prettier
        run: npx prettier --check .

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present 

  # connect-to-vpn:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: catthehacker/ubuntu:act-latest
  #     credentials:
  #       username: root
  #       password: example
  #     options: privileged

  #   steps:
  #     - uses: actions/checkout@v1
  #       with:
  #         fetch-depth: 1

  #     - name: Update
  #       run: sudo apt update

  #     - name: Install openconnect
  #       run: sudo apt install -y openconnect

  #     - name: Connect to VU VPN

